name: Artifact download

on:
  workflow_call:

jobs:
  artifact:
    runs-on: ubuntu-22.04

    steps:     
      - name: Download artifact
        uses: actions/download-artifact@v4  
        with: 
          name: current date
      - run: ls -Rla
      - run: cat to_upload.txt